### ISSUE TITLE
Bug report: Typo in sequence type option and issue with multiple inputs for number of machines

### ISSUE THREAD

**Issue by qzheng75** [genomicepidemiology/SpanSeq#1]
Thank you for developing this useful tool for data splitting. While using SpanSeq to split a dataset of protein sequences, I've encountered two issues:

1. Typo in sequence type option:
   In `spanseq.py` at line 88, there appears to be a discrepancy in the `choices` for the `-s` / `--seqtype` argument:

```
data_arg.add_argument("-s", "--seqtype", type=str, required=True,
                   choices=["nucleotides", "aminoacids"], help=("Type of "
                   "sequence at the fasta file. The options are 'nucleotides'"
                   " and 'aminoacid'"))
```
The choices list includes "aminoacids" (plural), but the help text specifies 'aminoacid' (singular). This inconsistency may cause confusion or errors when users try to specify -s aminoacid.

2. Multiple inputs not working for `-b` option:
The documentation suggests that multiple inputs are supported for the -b flag. However, I've been unable to successfully use this feature. I've tried the following inputs without success:
- `-b 0.1 0.9`
- `-b 10 90`
- Using commas to separate the numbers

Could you please clarify if this feature has been implemented? If so, what is the correct syntax for providing multiple boundary inputs?

I appreciate your attention to these issues and look forward to your response. Thank you for your continued work on SpanSeq.

**Comment by ffalfred** [comment]
Sorry for the late answer.

Thank you for finding those issues. They have been solved with the last commit.

A much stable version of SpanSeq will be released at the end of the year (better interface, same results)
